### ISSUE TITLE
Purpose of method `getAllValues`

### ISSUE THREAD

**Issue by FloMiLe** [jsxgraph/moodleformulas_jsxgraph#1]
I am wondering about the purpose of the method `getAllValues`.

First, in the README.md, it says that the method is of type {void}, which seems wrong to me as it actually is supposed to return an array of values.

Second, in the given example, it is used as `[t1, t2, t3, t4] = question.getAllValues(4, 0);`. Should the argument not be an array in order to properly set `defaultValues`? With this line in place, all initial values `[t1, t2, t3, t4]` are set to 4.

Third, even when the method is called without any arguments, `[t1, t2, t3, t4]` are not initialized to `[y1, y2, y3, y4]` provided in the "Answer" field. (Is this what is meant by "Fetch all values from the formulas input fields."?)

Fourth, what would even be the purpose of initializing `[t1, t2, t3, t4]` to the correct solutions?

**Comment by walterandreas** [comment]
Dear FloMiLe!

Thanks for your post. To your questions:

1. An error has actually crept into the `README` file. It was correctly documented in the comments of the method (directly in the `JSXQuestion.js` file).

2. The given line in the example (`[t1, t2, t3, t4] = question.getAllValues ​​(4, 0);`) queries the values ​​of the inputs from formulas. That is why the method is called "`get`". If you want to set the values, the method `setAllValues` ​​("`set`"!) must be used. Second function can have an array of values ​​as input or a single value that applies to all fields. Standard or initial values ​​are usually set by formulas. The given line of code does not set the value to `4` ("`get`"!), but asks for the _actual_ value of the input. Only if the input value could not be read (and really only then) the transferred standard value (here: `4`) is returned in order not to produce any "`NaN`" entries.

3. Here I refer again to "`get`". The method reads the input fields (fetch = another word for get). To initialize `[t1, t2, t3, t4]` with the values `​​[y1, y2, y3, y4]` at the beginning would be counterproductive in this project, since this would mean that the solution is presented at the beginning. If you want to set the values ​​initially (to any value you want), you can either use formulas or the call of `setAllValues`.

4. Exactly that is the question! That's why the values ​​are only read here ;-)

I'll close the issue. If I haven't fully helped you, just reopen it.

Andreas
